server:
  port: 24001
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: hidoc-app

  #  main:
  #    allow-bean-definition-overriding: true #启用覆盖同名bean
  # 数据库相关配置
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/hidoc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.81.139:5432/hidoc
    username: postgres
    password: HIdev210704
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 3
    minIdle: 3
    maxActive: 5
    keepAlive: true
    # 配置获取连接等待超时的时间
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenLogStatsMillis: 120000
    # ++++++++++++++++++++++++++++++++++++++++++++++++++++


#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
  #    # druid相关配置
  #    druid:
  #      # 连接池初始化大小
  #      initial-size: 8
  #      # 最大活跃连接数
  #      max-active: 20
  #      # 最小空闲连接数
  #      min-idle: 1
  #      # 获取连接等待超时的时间
  #      max-wait: 60000
  #      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，ms
  #      time-between-eviction-runs-millis: 60000
  #      validation-query: select 'x'
  #      # 配置过滤器，https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
  #      filters: stat,slf4j,config
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    servlet:
      load-on-startup: 1
  cache:
    jcache:
      config: classpath:config/ehcache.xml

# mybatis-plus 输出 SQL 语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#日志记录
logging:
  config: classpath:config/log4j2.xml
#  level:
#    com.hisense.rop.portal.mapper: debug
#    com.chz.mapper: debug
#    com.example.demo.dao: debug